// Client-side Mailchimp subscription helper.
//
// Uses Mailchimp's classic embedded-form JSONP endpoint so the user stays on
// our site instead of being redirected to Mailchimp's hosted "Thanks" page.
// All config below comes from the embed snippet generated by Mailchimp's form
// builder for the Tally audience.

export const MAILCHIMP_CONFIG = {
  baseUrl: "https://tally-group.us19.list-manage.com",
  u: "d58a2da09f1ed0a7b339fe7ef",
  id: "fd6a4137bc",
  fId: "00f688e3f0",
} as const;

// Mailchimp expects a hidden input named `b_<u>_<id>` to be present and empty;
// bots that auto-fill every field will populate it and get rejected.
export const MAILCHIMP_HONEYPOT_NAME =
  `b_${MAILCHIMP_CONFIG.u}_${MAILCHIMP_CONFIG.id}` as const;

export type MailchimpRegion = "AU" | "US" | "JP" | "AE" | "AE-EN";

export type MailchimpSubscribeInput = {
  email: string;
  firstName?: string;
  lastName?: string;
  company?: string;
  region?: MailchimpRegion;
  honeypot?: string;
};

export type MailchimpSubscribeResult = {
  ok: boolean;
  alreadySubscribed: boolean;
  rawMessage: string;
};

let callbackCounter = 0;

export async function subscribeToMailchimp(
  input: MailchimpSubscribeInput,
  timeoutMs = 10000,
): Promise<MailchimpSubscribeResult> {
  if (typeof window === "undefined") {
    throw new Error("subscribeToMailchimp must be called from the browser");
  }

  const callbackName = `__mcCallback_${Date.now()}_${++callbackCounter}`;

  const params = new URLSearchParams({
    u: MAILCHIMP_CONFIG.u,
    id: MAILCHIMP_CONFIG.id,
    f_id: MAILCHIMP_CONFIG.fId,
    c: callbackName,
    EMAIL: input.email,
    FNAME: input.firstName ?? "",
    LNAME: input.lastName ?? "",
    COMPANY: input.company ?? "",
    [MAILCHIMP_HONEYPOT_NAME]: input.honeypot ?? "",
  });

  // To track region (AU / US / JP / AE / AE-EN) in Mailchimp:
  //   1. Mailchimp ? Audience ? Settings ? Audience fields and *|MERGE|* tags
  //   2. Add a Text field with merge tag `REGION` (visibility can be hidden)
  //   3. Uncomment the line below.
  if (input.region) params.set("REGION", input.region);

  const url = `${MAILCHIMP_CONFIG.baseUrl}/subscribe/post-json?${params.toString()}`;

  return new Promise<MailchimpSubscribeResult>((resolve) => {
    const script = document.createElement("script");
    let timeoutId: number | undefined;

    const cleanup = () => {
      if (timeoutId !== undefined) window.clearTimeout(timeoutId);
      script.remove();
      delete (window as unknown as Record<string, unknown>)[callbackName];
    };

    (window as unknown as Record<string, unknown>)[callbackName] = (
      data: { result?: string; msg?: string } | undefined,
    ) => {
      const rawMessage = (data?.msg ?? "").toString();
      const alreadySubscribed = /already subscribed/i.test(rawMessage);
      cleanup();
      if (data?.result === "success") {
        resolve({ ok: true, alreadySubscribed: false, rawMessage });
      } else if (alreadySubscribed) {
        resolve({ ok: true, alreadySubscribed: true, rawMessage });
      } else {
        resolve({ ok: false, alreadySubscribed: false, rawMessage });
      }
    };

    script.src = url;
    script.async = true;
    script.onerror = () => {
      cleanup();
      resolve({
        ok: false,
        alreadySubscribed: false,
        rawMessage: "Network error. Please try again.",
      });
    };

    timeoutId = window.setTimeout(() => {
      cleanup();
      resolve({
        ok: false,
        alreadySubscribed: false,
        rawMessage: "Request timed out. Please try again.",
      });
    }, timeoutMs);

    document.body.appendChild(script);
  });
}
